// Os 38 ângulos de campanha (html 336-373). Ordem preservada.
export const ANGULOS: readonly string[] = [
  'Empreendimento específico',
  'Bairro ou região',
  'Proximidade com metrô',
  'Dor do aluguel',
  'Primeiro imóvel',
  'Financiamento facilitado',
  'Oportunidade de preço',
  'Escassez',
  'Investimento',
  'Valorização',
  'Renda com locação',
  'Lifestyle',
  'Conveniência',
  'Família',
  'Upgrade de vida',
  'Status e exclusividade',
  'Arquitetura e design',
  'Incorporadora',
  'Segurança da compra',
  'Urgência de decisão',
  'Comparativo',
  'Educativo',
  'Perda de oportunidade',
  'Independência e conquista',
  'Tempo de vida',
  'Mobilidade',
  'Produto compacto inteligente',
  'Segunda residência',
  'Patrimônio',
  'Lead de alta intenção',
  'Evento ou ativação',
  'Corretor especialista',
  'Curadoria',
  'Diagnóstico',
  'Erro comum',
  'Aluguel vs. financiamento/investimento',
  'Momento de vida',
  'Aquisição de corretores para a Boxys',
]

// Selects do briefing (html 01: segmento, estágio).
export const SEGMENTOS: readonly string[] = [
  'MCMV',
  'Econômico',
  'Médio padrão',
  'Médio-alto',
  'Alto padrão',
  'Luxo',
  'Ultra luxo',
  'Studios',
  'Investidores',
  'Segunda residência',
]

export const ESTAGIOS: readonly string[] = [
  'Lançamento',
  'Em construção',
  'Pronto para morar',
  'Aluguel',
]
