// Histórico de atualizações do gerador (html 634-669). A versão exibida é CHANGELOG.length.
export const CHANGELOG: readonly string[] = [
  'Versão inicial: formulário de briefing + geração de campanha completa em uma única chamada.',
  'Adicionados os 10 segmentos reais da Boxys e os 38 ângulos de campanha selecionáveis (chips).',
  "Separado 'Estágio do empreendimento' (Lançamento/Em construção/Pronto para morar/Aluguel) do campo de Segmento.",
  'Adicionado upload de material de referência (PDF e imagens) + campo de links/observações de sites.',
  "Adicionado modo 'Preço por tipologia' com comissionamento do corretor calculado automaticamente (% → R$).",
  "Preço por tipologia passou a ser calculado por metragem × valor do m², em vez de preço direto.",
  "Mesma lógica de metragem × valor do m² aplicada também ao modo 'Preço de entrada/referência'.",
  'Corrigido botão de copiar (fallback para navegadores sem Clipboard API) e adicionados botões de baixar .md e PDF.',
  'Implementados IDs únicos por peça, no padrão {CÓDIGO_CAMPANHA}-{TIPO}-{DESTINO}-{SEQ}.',
  'Corrigido bug de referência a checkboxes removidos que quebrava a geração.',
  'Reestruturado o fluxo inteiro em mesas de especialistas: Mesa de Estratégia (3 opções) antes de qualquer copy.',
  'Bloco de Ads dividido em chamadas menores para não estourar limite de tokens, depois simplificado para já nascer em formato de importação.',
  'Corrigido formato do Google Search/Display/PMax para multi-linha numerado (padrão real de Google RSA), igual à clareza do Meta.',
  'Adicionado bloco de Vídeos (mesa de casting + 6 templates de anúncio + 2 cinematográficos).',
  'Adicionado bloco de Redes Sociais (mesa de roteiro/copy orgânico + carrosséis + estáticos/status), depois dividido em botões independentes por parte.',
  'Adicionado bloco de Landing Page com dupla mesa (UX decide estrutura → Copy escreve em cima), dividido em Parte 1 e Parte 2.',
  'Adicionado bloco de App/Teaser (mesa institucional Boxys + conteúdo do app + teaser cinematográfico de 45s).',
  'Adicionados os blocos de Tráfego Pago (Meta, Google, TikTok, LinkedIn, Pinterest, X) e Síntese das Estratégias Utilizadas.',
  'Bloco de Tráfego Pago condicionado a Ads e Landing Page já gerados, recebendo o contexto das 6 mesas anteriores.',
  'Incluídos os Vídeos como pré-requisito/contexto do Tráfego Pago e corrigido bug estrutural de parsing de JSON (quebras de linha dentro de strings) em todas as mesas.',
  'Adicionado badge de versão e histórico de atualizações no cabeçalho.',
  'Corrigido de vez o parsing de JSON das mesas: heurística de aspas soltas dentro de strings + retry automático com mais tokens quando a resposta vem cortada ou malformada.',
  "Adicionado 'Salvar progresso' e 'Continuar campanha salva' — exporta/importa todo o estado da campanha (formulário, decisões das mesas e textos já gerados) em um arquivo .json.",
  "Corrigido retry da mesa de tráfego pago para cobrir falhas reais da API (não só JSON malformado), exposto o erro real da API em vez de 'resposta vazia' genérico, e reduzido o contexto da deliberação (mesa) para um resumo — só as gerações finais usam o texto completo de Ads/Vídeos/LP.",
  'Adicionado novo passo 05 — Mesa de Perfil de Público (Alan Cooper, Clayton Christensen, Clotaire Rapaille, Byron Sharp), antes da Mesa de Estratégia: propõe 3 perfis com job-to-be-done, código emocional e comportamento de mídia, e o perfil escolhido passa a ser herdado por todas as mesas seguintes.',
  "Incluído o perfil de público no 'Salvar progresso'/'Continuar campanha salva', que ainda não estava contemplando essa decisão.",
  'Mesa de Perfil de Público passou a permitir seleção múltipla (a mesma campanha pode ter mais de um público) — cards viram checáveis, com botão de confirmação; todas as mesas seguintes agora recebem a lista de perfis, não mais um único perfil.',
  "Adicionado painel 'Peça um ajuste' abaixo do documento gerado: escolhe qual bloco já feito quer corrigir, escreve a observação, e o sistema reescreve só aquele bloco (mantendo IDs e estrutura) sem precisar regenerar a campanha inteira. Também salvo/restaurado via 'Salvar progresso'.",
  'Adicionada nova seção 05 — Restrições e Informações Extras: restrições viram regras negativas absolutas em toda a campanha, informações extras entram como contexto adicional — ambas fluem automaticamente para todas as mesas e blocos.',
  'Adicionado ajuste com feedback também nas mesas de Perfil de Público e Estratégia (que geram opções, não texto final): caixa de observação + botão que gera 3 opções novas considerando o que não agradou nas anteriores.',
  'Adicionado Calibrador de Estilo de Copy (seção 06): calibra por exemplo (cola textos ideais e uma mesa extrai comprimento de frase, ritmo, pontuação, vocabulário recorrente e o que evitar) ou por atributos manuais (formalidade, comprimento, agressividade do CTA, uso de dados, ritmo). O perfil resultante é editável e entra automaticamente em toda copy gerada da campanha, coexistindo com o tom escolhido em cada mesa. Válido por campanha, salvo/restaurado junto com a sessão.',
  'Mesa de casting de vídeo (bloco Vídeos) passou a permitir seleção múltipla de arquétipos, mesmo padrão da Mesa de Perfil de Público — os vídeos cinematográficos podem usar personagens diferentes entre si.',
  "Todos os botões de 'Gerar' (Ads, Vídeos, Redes Sociais, LP, App, Tráfego Pago, Síntese) agora mostram um selo '✓ Gerado' depois da primeira geração, e '✓ Gerado (Nx)' se forem clicados de novo — sinalização visual de que aquele bloco já tem conteúdo e quantas vezes foi regenerado.",
  'Adicionados Bill Bernbach, David Abbott e Howard Gossage à mesa de Copywriting (Ads e Calibrador de Estilo).',
]
